apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd
    app: etcd
  name: etcd
  namespace: etcd
spec:
  clusterIP: None
  ports:
  - name: grpc-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: grpc-peer
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    k8s-app: etcd
    app: etcd
  type: ClusterIP
